services:
  db:
    image: postgres:12.2-alpine
    restart: always
    env_file:
      - .env
    networks:
      - wand
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./houdini/sql:/docker-entrypoint-initdb.d
      - ./.data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    restart: always
    env_file:
      - .env
    networks:
      - wand
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf", "--requirepass", "${REDIS_PASSWORD}"]
  dash:
    build: ./dash
    restart: always
    env_file:
      - .env
    networks:
      - wand
    volumes:
      - ./dash:/usr/src/dash
      - ./vanilla-media/media/avatar/paper:/usr/src/dash/items
      - ./templates/dash/config.py.template:/usr/src/dash/config.py.template
    depends_on:
      - db
      - redis
    links:
      - db:db
      - redis:redis
      - houdini_login:login
    entrypoint: ["dockerize", "-wait", "tcp://login:${GAME_LOGIN_PORT}",
                "-template", "/usr/src/dash/config.py.template:/usr/src/dash/config.py",
                "python", "bootstrap.py"]
    command: ["-c", "config.py"]
  web:
    build: ./web
    restart: always
    env_file:
      - .env
    networks:
      - wand
    ports:
      - ${WEB_PORT}:${WEB_PORT}
      - ${HTTPS_PORT}:${HTTPS_PORT}
    volumes:
      - ./www:/usr/share/nginx/html
      - ./vanilla-media:/usr/share/nginx/vanilla
      - ./templates/nginx:/t/etc/nginx/conf.d:ro
      - ./templates/vanilla:/t/usr/share/nginx/vanilla:ro
      - ./ruffle/web/packages/selfhosted/dist:/ruffle:ro
      - ${SSL_KEYS_DIR}:${SSL_KEYS_DIR}:ro
    links:
      - dash:dash
  houdini_login:
    build: ./houdini
    restart: always
    env_file:
      - .env
    networks:
      - wand
    ports:
      - ${GAME_LOGIN_PORT}:${GAME_LOGIN_PORT}
      - ${GAME_LOGIN_WEBSOCKET}:${GAME_LOGIN_WEBSOCKET}
    volumes:
      - ./houdini:/usr/src/houdini
      - ./wait-for-postgres.sh:/usr/local/bin/wait-for-postgres.sh:ro
      - ${SSL_KEYS_DIR}:/usr/src/houdini/keys:ro
    depends_on:
      - db
      - redis
    links:
      - db:db
      - redis:redis
    entrypoint: ["dockerize", "-wait", "tcp://redis:6379", "wait-for-postgres.sh", "db", "python", "bootstrap.py", "login"]
    command: ["--port", "${GAME_LOGIN_PORT}",
              "--redis-address", "redis",
              "--database-address", "db",
              "--database-user", "${POSTGRES_USER}",
              "--database-name", "${POSTGRES_USER}",
              "--database-password", "${POSTGRES_PASSWORD}",
              "--redis-password", "${REDIS_PASSWORD}",
              "--logging-level", "${SERVER_LOG_LEVEL}"]
  houdini_blizzard:
    build: ./houdini
    restart: always
    env_file:
      - .env
    networks:
      - wand
    ports:
      - 9875:9875
      - 10875:10875
    volumes:
      - ./houdini:/usr/src/houdini
      - ${SSL_KEYS_DIR}:/usr/src/houdini/keys:ro
    depends_on:
      - houdini_login
    links:
      - db:db
      - redis:redis
      - houdini_login:login
    entrypoint: ["dockerize", "-wait", "tcp://login:${GAME_LOGIN_PORT}", "python", "bootstrap.py", "world"]
    command: ["-id", "3100", "--name", "blizzard", "--port", "9875", "--lang", "en",
              "--redis-address", "redis",
              "--database-address", "db",
              "--database-user", "${POSTGRES_USER}",
              "--database-name", "${POSTGRES_USER}",
              "--database-password", "${POSTGRES_PASSWORD}",
              "--redis-password", "${REDIS_PASSWORD}",
              "--logging-level", "${SERVER_LOG_LEVEL}"]
  snowflake:
    build: ./snowflake
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
      - MEDIA_LOCATION=${WEB_VANILLA_MEDIA}
      - PORT=${SNOWFLAKE_PORT}
      - ENABLE_DEBUG_LOGGING=${SNOWFLAKE_LOGGING_ENABLED}
      - WEBSOCKET_ENABLED=True
      - WEBSOCKET_PORT=${SNOWFLAKE_WS_PORT}
      - WEBSOCKET_SSL_ENABLED=${TLS_ENABLED}
      - WEBSOCKET_SSL_KEYFILE=keys/${KEY_FILE_PEM}
      - WEBSOCKET_SSL_CERTFILE=keys/${CERT_FILE_PEM}
    networks:
      - wand
    ports:
      - ${SNOWFLAKE_PORT}:${SNOWFLAKE_PORT}
      - ${SNOWFLAKE_WS_PORT}:${SNOWFLAKE_WS_PORT}
    volumes:
      - ./snowflake:/usr/src/snowflake
      - ./.env:/usr/src/snowflake/.env
      - ${SSL_KEYS_DIR}:/usr/src/snowflake/keys:ro
    depends_on:
      - db
      - redis
      - dash
    links:
      - db:db
      - redis:redis
      - houdini_login:login
    entrypoint: ["dockerize", "-wait", "tcp://login:${GAME_LOGIN_PORT}", "python", "./main.py"]

networks:
  wand:
    driver: bridge
